repos:
  - repo: local
    hooks:
      - id: dart-format-fix-analyse
        name: Format, fix and analyse Dart/Flutter
        language: system
        entry: dart tool/lint_and_fix.dart
        pass_filenames: false
