name: truly_budget
description: A clean Flutter budget app — TrulyBudget
publish_to: 'none'
version: 0.7.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.67.0
  url_launcher: ^6.2.6
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  
dev_dependencies:
  flutter_lints: ^3.0.1 

flutter:
  uses-material-design: true
